name: build-publish

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run publish
    - name: Pushes to public website repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'dist'
        destination-github-username: ${{ secrets.USERNAME_GITHUB_COMMIT }}
        destination-repository-name: ${{ secrets.PROD_REPO }}
        user-email: ${{ secrets.EMAIL_GITHUB_COMMIT }}